

export const types = {

    USER_LOADED: '[CHAT] USER_LOADED',
    SET_ACTIVE_CHAT: '[CHAT] SET_ACTIVE_CHAT',
    SET_MESSAGE: '[CHAT] NEW_MESSAGE',
    UPLOAD_MESSAGES: '[CHAT] UPLOAD_MESSAGES',
    CLEAR_CHAT: '[CHAT] CLEAR_CHAT'
}